apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: donation-api
  namespace: gregorie769-dev
spec:
  runPolicy: SerialLatestOnly

  source:
    type: Git
    git:
      uri: git@github.com:gregorie769-star/company-ma-inner-api-donation.git
      ref: master
    sourceSecret:
      name: github-ssh-secret

  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        namespace: openshift
        name: ubi8-openjdk-17:1.18

      env:
        - name: MAVEN_ARGS
          value: "-DskipTests"

  output:
    to:
      kind: ImageStreamTag
      name: donation-api:latest

  triggers: []
