// app parameters
application.name=myc-ma-inner-api-donation
application.groupId=ma/myc/inner/donation
git.url=https://github.myc.com/myc-ma/myc-ma-inner-api-donation.git

// Contact Ops team to get available port
application.port=8080 

// ops parameters
server.dev.user=apiuser
server.dev.ip=10.62.0.185
server.dev.sshkey=apiuser-10.62.0.185-SRV-API-INNER2
server.uat.user=apiuser
server.uat.ip=10.62.0.87
server.uat.sshkey=apiuser-10.62.0.87-SRV-API-INNER

server.preprod.ips=10.62.0.84;10.62.0.184
server.preprod.user=apiuser
server.preprod.sshkey=PREPROD_API_APIUSER_SSH_KEY

server.prod.ips=10.62.0.53;10.62.0.54;10.62.0.55;10.62.0.56
server.prod.user=apiuser
server.prod.sshkey=API_APIUSER_SSH_KEY

artifactory.maven=myc-ma_projects-maven
